# Generated by Django 3.0.3 on 2020-04-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.IntegerField(default=0)),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_salary', models.IntegerField(default=0)),
                ('employee_age', models.IntegerField(default=0)),
                ('profile_img', models.ImageField(upload_to=None)),
            ],
        ),
    ]
