# Generated by Django 3.0.3 on 2020-04-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200416_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
    ]
