# Generated by Django 3.0.3 on 2020-04-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20200416_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_img',
            field=models.ImageField(default=1, upload_to=''),
        ),
    ]
