# Generated by Django 3.0.3 on 2020-04-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20200416_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_img',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
